# Generated by Django 5.1 on 2024-09-06 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date=models.DateTimeField(default=django.utils.timezone.now)),
            preserve_default=False,
        ),
    ]
